### PR TITLE
[FIX] MacOS Screenshot for README (#12)

### LINKED ISSUE #12: MacOS notification Screenshot in README
- [ ] need a sample notification screenshot for macOS notification

### PR DESCRIPTION
**Pull request by Aron-R**
Hey there, I happened to include the MacOS screenshot for the read me 
I hope it’s fine ❤️

Issue number: #12
Issue: MacOS notification Screenshot in README 
Fixes #12

### CODE REVIEW

**Comment by Abhiroop25902** [comment]
From this [Wikipedia link](https://en.wikipedia.org/wiki/.DS_Store), I found that .DS_Store files are not related to the repo, can you please remove it from the PR ?

**Comment by arnabsen1729** [comment]
You can either remove `.DS_Store` or add it to the `.gitignore`

**Comment by Aron-R** [comment]
@Abhiroop25902 @arnabsen1729 
Sure

**Comment by Aron-R** [comment]
@Abhiroop25902 @arnabsen1729 
I hope it’s fine now

**Comment by arnabsen1729** [comment]
LGTM :+1:

**Pull request merged**
