### PR TITLE
[NEW] Basic Implementation of Todo CLI

### PR DESCRIPTION
**Pull request by Abhiroop25902**
Added basic functionality of the Todo CLI, which include adding and deleting Todo and their deadlines

### CODE REVIEW

**Comment by arnabsen1729** [comment]
use `flake8` or `pep` for linting purpose

**Comment by arnabsen1729** [comment]
@Abhiroop25902 also add me to the maintainers I will be actively reviewing this repo.

**Comment by Abhiroop25902** [comment]
Affirmative, on it

**Comment by Abhiroop25902** [comment]
@arnabsen1729 added you as a maintainer, and also used flake8 linter to reformat the code base

**Comment by arnabsen1729** [comment]
LGTM

**Pull request merged**
