### PR TITLE
[New] Create Interactive Interface

### PR DESCRIPTION
**Pull request by IanFindlay**
Addressing at least some part of issue #2, this PR establishes an interactive interface for the program using a While true loop and argparse to allow the triggering of various commands related to the to-do list.

Still to do:
- [x] Move thread creation and execution out of the loop
- [x] Write docstring for parse_command() and help text for some of the parser's arguments
- [x] Remove test todo items
- [x] Change "deadline reached" format
- [x] Command prompt reappears after "deadline reached"
- [x] View of an empty todo list prints that there are no todos
- [x] Make multi-word command passing clear or revert to input prompts

Might also:
- [x] Start/finish the view branch of the program
- [x] Improve the display of todo's whose deadlines have been reached

### CODE REVIEW

**Comment by IanFindlay** [comment]
With the exception of making deadlines truly optional (I've made them optional in terms of inputting the command but they still default to 1) which needs some design decisions and restructuring, I think I've addressed issue #2 and your feedback on my drafted approach. Let me know if there is anything wrong or any changes that you would suggest.

**Comment by Abhiroop25902** [comment]
Your PR LGTM, except the following problems:
- Currently the way Argument Parser works, the format to add a Todo is `add <heading> <description> <time>`. This approach allows only one word to be inserted as heading and description. Todos can have multiple word Heading and Descriptions.
    - A possible solution could be do add three different prompts, one for Heading, one for Description, and one for time
- The "deadline reached" representation of a Todo is as follows
    - image
    - There's a newline between heading and description
    - I guess this format will be better: 
        - ```
          Deadline for task '<Heading>' has been reached
          It's Description is '<Description>'
          ```
- After printing a Todo, the prompt doesn't come back
    - ![image](https://user-images.githubusercontent.com/69428539/136737028-293cd40c-830b-47af-9ab8-76a09bbbccca.png)
    - One Possible Solution could be to reprinting the prompt after printing the Todo
- If there is no Todo Present, `view` command just prints out a bunch of newlines
    - ![image](https://user-images.githubusercontent.com/69428539/136737487-bda2a6cd-d8dd-48c2-8719-100fdf89b912.png)
    - Adding some prompt like `No Todo Present` will be more straightforward I guess



Additional Note:
- After these fixes, I think this will be a good time to remove the example Todo Insertions now that an interface has been created
- Great Work !!!!!

**Comment by Abhiroop25902** [comment]
LGTM, just update the tick marks in README.md and I will merge this to main

Great Work !!!!!

**Comment by IanFindlay** [comment]
> LGTM, just update the tick marks in README.md and we will merge this to main branch

Done - thanks for the reviews and kind comments.

**Comment by Abhiroop25902** [comment]
Thanks a lot for this contribution, we can't thank you enough

**Pull request merged**
